# Generated by Django 2.2.6 on 2020-05-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sramais', '0010_remove_ramais_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramais',
            name='Função',
            field=models.CharField(choices=[('Estagiário(a)', 'Estagiário(a)'), ('Funcionário(a)', 'Funcionário(a)'), ('Temporário(a)', 'Temporário(a)'), ('Terceirizado(a)', 'Terceirizado(a)')], max_length=25, null=True, verbose_name='Função'),
        ),
    ]
